# Generated by Django 5.0.4 on 2024-04-26 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pogoda', '0003_city_content_city_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
    ]
